services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 123123
    ports:
      - 1234:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: