services:
  db:
    image: postgres
    restart: always
#    command: >
#      bash -c "psql -h localhost -U postgres -c "create database hami_postgres""
    environment:
      POSTGRES_PASSWORD: 123123
    ports:
      - 1234:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: