services:
    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: 123123
        ports:
            - 1234:5432
        volumes:
            - pgdata:/var/lib/postgresql/data
    dbsetup:
        image: postgres
        environment:
            PGPASSWORD: 123123
        depends_on:
            - db
        restart: "no"
        entrypoint:
            [
                "sh",
                "-c",
                "echo \"SELECT 'CREATE DATABASE hermes_postgres' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'hermes_postgres')\\gexec\" | psql -h db -U postgres",
            ]
volumes:
    pgdata:
